### PR TITLE
Version bump. Add the spec dir as well

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by quixoten** [comment]
Because the code is not developed in this repo, I don't see the need to keep the specs here. What's your reasoning on this?

**Comment by tampakrap** [comment]
my distro generates packages based on gems, so having the rspec tests in this repo means I can have them in the gem, thus running them in my package as well

**Comment by quixoten** [comment]
can you codify the addition of the specs so it happens as part of `rake sync_with_upstream` ?

**Comment by tampakrap** [comment]
I added it, and also the rspec rake tasks. For the record, this seems incomplete, the tests still fail and I'm trying to figure out why, but as you said the code is not developed here so feel free to merge it for now :)

**Comment by quixoten** [comment]
The only real change here is the additions of the specs (the code hasn't changed despite the version bump), so I'm hesitant to merge this knowing that the only thing that's changed is broken. If for some reason you require the version to be bumped, I'd be happy to merge a PR that's limited to that.

**Comment by tampakrap** [comment]
sure, I removed the addition of the tests, I left only the version bump and the license fix

**Comment by quixoten** [comment]
released.

**Pull request merged**
